### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by privettoli** [pjjjv/app-router-dart#1]
[Warning from ImportInliner on Project|web/index.html]:
line 46, column 13 of web/index.html: (from html5lib) Unexpected character after attribute value. See http://goo.gl/5HPeuP#polymer_40 for details.
<app-route path="/settings" imp="elements/sw-page-settings/sw-page-settings.html" [element="sw-page-settings"]

**Comment by pjjjv** [comment]
First of all `element` should be `elem`. Second, those square brackets should not be used in html.

I'm sorry if my documentation (app-router-dart-test) is still of bad quality. Does this help though?
